# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dacq
else:
    import _dacq

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def dacq_start(boot, testmode, tracker_type, dacq_server, arg1, arg2):
    return _dacq.dacq_start(boot, testmode, tracker_type, dacq_server, arg1, arg2)

def dacq_stop():
    return _dacq.dacq_stop()

def dacq_release():
    return _dacq.dacq_release()

def dacq_dig_in(n):
    return _dacq.dacq_dig_in(n)

def dacq_dig_out(n, val):
    return _dacq.dacq_dig_out(n, val)

def dacq_str_word(val):
    return _dacq.dacq_str_word(val)

def dacq_eye_x():
    return _dacq.dacq_eye_x()

def dacq_eye_y():
    return _dacq.dacq_eye_y()

def dacq_eye_params(xgain, ygain, xoff, yoff):
    return _dacq.dacq_eye_params(xgain, ygain, xoff, yoff)

def dacq_eye_read(which):
    return _dacq.dacq_eye_read(which)

def dacq_ad_n(n):
    return _dacq.dacq_ad_n(n)

def dacq_ts():
    return _dacq.dacq_ts()

def dacq_bar():
    return _dacq.dacq_bar()

def dacq_bar_transitions(reset):
    return _dacq.dacq_bar_transitions(reset)

def dacq_bar_genint(b):
    return _dacq.dacq_bar_genint(b)

def dacq_sw1():
    return _dacq.dacq_sw1()

def dacq_sw2():
    return _dacq.dacq_sw2()

def dacq_juice(on, dobeep, dojuice):
    return _dacq.dacq_juice(on, dobeep, dojuice)

def dacq_juice_drip(ms, dobeep, dojuice):
    return _dacq.dacq_juice_drip(ms, dobeep, dojuice)

def dacq_fixbreak_tau(n):
    return _dacq.dacq_fixbreak_tau(n)

def dacq_fixwin(n, cx, cy, radius, vbias):
    return _dacq.dacq_fixwin(n, cx, cy, radius, vbias)

def dacq_fixwin_genint(n, b):
    return _dacq.dacq_fixwin_genint(n, b)

def dacq_fixwin_reset(n):
    return _dacq.dacq_fixwin_reset(n)

def dacq_fixwin_state(n):
    return _dacq.dacq_fixwin_state(n)

def dacq_fixwin_broke(n):
    return _dacq.dacq_fixwin_broke(n)

def dacq_fixwin_break_time(n):
    return _dacq.dacq_fixwin_break_time(n)

def dacq_adbuf_toggle(on):
    return _dacq.dacq_adbuf_toggle(on)

def dacq_adbuf_clear():
    return _dacq.dacq_adbuf_clear()

def dacq_adbuf_size():
    return _dacq.dacq_adbuf_size()

def dacq_adbuf_t(ix):
    return _dacq.dacq_adbuf_t(ix)

def dacq_adbuf_x(ix):
    return _dacq.dacq_adbuf_x(ix)

def dacq_adbuf_y(ix):
    return _dacq.dacq_adbuf_y(ix)

def dacq_adbuf_pa(ix):
    return _dacq.dacq_adbuf_pa(ix)

def dacq_adbuf_c0(ix):
    return _dacq.dacq_adbuf_c0(ix)

def dacq_adbuf_c1(ix):
    return _dacq.dacq_adbuf_c1(ix)

def dacq_adbuf_c2(ix):
    return _dacq.dacq_adbuf_c2(ix)

def dacq_adbuf_c3(ix):
    return _dacq.dacq_adbuf_c3(ix)

def dacq_adbuf_c4(ix):
    return _dacq.dacq_adbuf_c4(ix)

def dacq_adbuf_photo(ix):
    return _dacq.dacq_adbuf_photo(ix)

def dacq_adbuf_spikes(ix):
    return _dacq.dacq_adbuf_spikes(ix)

def dacq_eye_smooth(kn):
    return _dacq.dacq_eye_smooth(kn)

def dacq_set_pri(dacq_pri, iscan_pri):
    return _dacq.dacq_set_pri(dacq_pri, iscan_pri)

def pp_init(base):
    return _dacq.pp_init(base)

def pp_bar():
    return _dacq.pp_bar()

def pp_sw1():
    return _dacq.pp_sw1()

def pp_sw2():
    return _dacq.pp_sw2()

def pp_sw3():
    return _dacq.pp_sw3()

def pp_juice(on):
    return _dacq.pp_juice(on)

def pp_juice_drip(ms):
    return _dacq.pp_juice_drip(ms)

def pp_out(x):
    return _dacq.pp_out(x)

def dacq_set_rt(rt):
    return _dacq.dacq_set_rt(rt)

def dacq_seteuid(uid):
    return _dacq.dacq_seteuid(uid)

def dacq_set_mypri(pri):
    return _dacq.dacq_set_mypri(pri)

def dacq_int_class():
    return _dacq.dacq_int_class()

def dacq_int_arg():
    return _dacq.dacq_int_arg()

