#!/bin/sh
set -e
### if [ $(whoami) != "root" ]; then
###   echo "Are you sure you want to do this as $(whoami)?"
###   echo -n "hit ctrl-c to abort, return to continue"
###   read xxx
### fi

if [ "$1" = "-dir" ]; then
  export PYPEDIR=$2
  shift; shift
fi

if [ "$PYPEDIR" = "" ]; then
  echo "set PYPEDIR first"
  exit 0
fi
echo
export WHO=`/usr/bin/whoami`

### This is an old version ###
#---------------------------------------------------------------------
## No need to be fancy here. Python 2.7 is the last in the 2.0 series.
#export PYTHONVER="2"
#export PYTHONFULLVER="2.7"
#export PYTHONEXE=$(which python$PYTHONFULLVER)
#export PYTHONPREFIX=$(echo $PYTHONEXE | sed 's/\(.*\)\/bin.*/\1/')
#export PYPEDIR
#---------------------------------------------------------------------

### This is a new version to use Anaconda Python3 ###
export PYTHONVER="3"
export PYTHONEXE="/usr/bin/python3"
export PYTHONFULLVER=$(${PYTHONEXE} -c 'import sys; print(".".join(map(str, sys.version_info[0:2])))')

incdir=/usr/include/python$PYTHONFULLVER
libdir=/usr/lib/python$PYTHONFULLVER
libdir2=/usr/lib/python3/dist-packages

#libdir=$(${PYTHONEXE} -c "from distutils.sysconfig import get_python_lib; \
#		print(get_python_lib())" | xargs dirname)
#incdir=$(${PYTHONEXE} -c "from distutils.sysconfig import get_python_lib; \
#		print(get_python_lib())" | sed s/lib/include/g | xargs dirname)

export PYTHONINC=-I$incdir
#export PYCOMPILE=${PYTHONEXE} $libdir/compileall.py
#export LIBPYTHON=-l$libdir2

export PYPEDIR

/usr/bin/make -f Buildfile $*

